### ISSUE TITLE
Update maintainers on PyPI

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/zodburi#28]
Hey @chrisrossi, @jimfulton or @tseaver,

In your absence on this project, would it be possible to add any of the following people as owner on PyPI for this project:

- `xistence` - (me, @bertjwregeer) 
- `mmerickel` - @mmerickel 
- `pylonsbot` - release bot/continuance bot

There's been a request for someone else to step up and help maintain this project in the mean time, and it would be great if we can help things along in the mean time by reviewing and merging tickets/releasing new updates to PyPI.

Thank you,
Bert

**Comment by chrisrossi** [comment]
I didn't even realize I "owned" that. I have done as you ask. If Tres or
Jim thinks I did it wrong they can smack me around. I might even like it,
just a little bit.

Chris

**Comment by bertjwregeer** [comment]
@chrisrossi are there any other Pylons projects you are an owner on? That was going to be my next check, but since I've got a captive audience...

Thank you! I'll close this issue, I'm going to try and reach out to @tseaver and @jimfulton, I am making the assumption you have no qualms about potentially bringing on a new maintainer to help keep this project moving forward?

**Comment by chrisrossi** [comment]
The only thing I'm sole owner on, I think, is pyramid_layout. Happy to pass
it along.

**Comment by bertjwregeer** [comment]
@chrisrossi that'd be great. Same list of people :-)

**Comment by chrisrossi** [comment]
Ok. You asked for it.
